// Local preview against the LIVE Supabase backend.
// Reads .env (SUPABASE_URL + SUPABASE_ANON_KEY), serves the static dashboard and a
// dynamic /config.js that points window.SHORTLY.* at the DEPLOYED edge functions with
// the real anon key. The browser calls Supabase directly (functions allow CORS *).
// No agent token is injected, so the dashboard auto-unlocks and loads real data.
//
// Usage: node scripts/preview-server.mjs   ->   http://localhost:4173

import { createReadStream, existsSync, readFileSync } from "node:fs";
import { stat } from "node:fs/promises";
import { createServer } from "node:http";
import { extname, join, normalize, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PORT = Number.parseInt(process.env.PORT || "4173", 10);

// ---- load .env ----
function loadEnv() {
  const path = resolve(ROOT, ".env");
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    if (!process.env[m[1]]) process.env[m[1]] = v;
  }
}
loadEnv();

const SUPABASE_URL = (process.env.SUPABASE_URL || "").replace(/\/+$/, "");
const ANON = process.env.SUPABASE_ANON_KEY || "";
const ref = SUPABASE_URL.match(/https:\/\/(.+?)\.supabase\.co/)?.[1] || "";
if (!ref || !ANON || ANON.startsWith("YOUR_")) {
  console.error("Missing real SUPABASE_URL / SUPABASE_ANON_KEY in .env — cannot connect to live backend.");
  process.exit(1);
}
const fb = `https://${ref}.functions.supabase.co`;
const siteUrl = (process.env.SHORTLY_SITE_URL || "").replace(/\/+$/, "");
const dailyCap = parseInt(process.env.DAILY_CAP || "5", 10);

// verifyToken is intentionally omitted so the auth gate stays unlocked locally.
const CONFIG_JS = `// LOCAL preview -> LIVE Supabase (${ref}). Generated by preview-server.mjs.
window.SHORTLY = {
  list:            "${fb}/list-articles",
  review:          "${fb}/review-article",
  digest:          "${fb}/send-daily-digest",
  curatedDigest:   "${fb}/send-curated-digest",
  topicDigest:     "${fb}/send-topic-digest",
  submit:          "${fb}/send-article",
  subscribers:     "${fb}/subscribers",
  scrape:          "${fb}/scrape-news",
  summarize:       "${fb}/summarize-articles",
  corporateCase:   "${fb}/corporate-case-agent",
  editorialTopics: "${fb}/editorial-topic-agent",
  siteUrl:         "${siteUrl}",
  twitterUrl:      "https://x.com/Shortly_news",
  linkedinUrl:     "https://www.linkedin.com/company/shortly-news/",
  agentAppUrl:     "",
  anonKey:         "${ANON}",
  dailyCap:        ${dailyCap},
  reviewer:        "qa"
};
`;

const types = { ".css": "text/css; charset=utf-8", ".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8", ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg" };

createServer(async (req, res) => {
  const url = new URL(req.url || "/", `http://${req.headers.host}`);
  const pathname = url.pathname;
  if (pathname === "/config.js") { res.writeHead(200, { "Content-Type": types[".js"] }); return res.end(CONFIG_JS); }
  const filePath = normalize(join(ROOT, decodeURIComponent(pathname === "/" ? "/index.html" : pathname)));
  if (!filePath.startsWith(ROOT) || !existsSync(filePath)) { res.writeHead(404); return res.end("Not found"); }
  const info = await stat(filePath);
  if (!info.isFile()) { res.writeHead(404); return res.end("Not found"); }
  res.writeHead(200, { "Content-Type": types[extname(filePath)] || "application/octet-stream" });
  createReadStream(filePath).pipe(res);
}).listen(PORT, () => {
  console.log(`Shortly preview -> LIVE Supabase (${ref}): http://localhost:${PORT}`);
  console.log(`  Real data from the deployed edge functions. No mock data.`);
});
