-- Real delivery tracking for sent email.
--
-- WHY: article_deliveries.status = 'sent' only records that the provider
-- ACCEPTED the API call. It carries no delivery information at all. Two load
-- tests on 2026-08-15 both reported `sent: 100, failed: 0`:
--   run 1 -> 0 delivered   (address typo; every message hard-bounced)
--   run 2 -> 67 delivered  (Gmail throttled a 100-message burst)
-- The dashboard showed 100% success both times. If real subscribers began
-- silently failing, nothing in this system would notice.
--
-- This adds the missing feedback loop. Deliberately additive:
--   * new table email_events        -- append-only audit of provider callbacks
--   * new NULLABLE columns on article_deliveries
--   * no change to any send path
--
-- Suppression comes free: subscribers_status_check already allows 'bounced',
-- and every send filters on status = 'subscribed', so flagging a hard-bounced
-- address removes it from future sends without touching send-newsletter.

-- ---- 1. Append-only event audit ------------------------------------------
create table if not exists public.email_events (
  id           bigint generated by default as identity primary key,
  received_at  timestamptz not null default now(),
  provider     text not null default 'ses',
  message_id   text,                 -- provider message id (joins to article_deliveries)
  email        text,
  event_type   text not null,        -- delivery | bounce | complaint | reject | send | open | click
  bounce_type  text,                 -- Permanent | Transient | Undetermined
  bounce_sub   text,                 -- General | NoEmail | Suppressed | MailboxFull ...
  diagnostic   text,                 -- SMTP diagnostic code, when present
  raw          jsonb
);

create index if not exists email_events_message_id_idx on public.email_events (message_id);
create index if not exists email_events_email_idx      on public.email_events (lower(email));
create index if not exists email_events_received_idx   on public.email_events (received_at desc);

alter table public.email_events enable row level security;
revoke all on table public.email_events from anon, authenticated;

-- ---- 2. Outcome columns on the existing delivery log ---------------------
alter table public.article_deliveries
  add column if not exists delivered_at   timestamptz,
  add column if not exists bounced_at     timestamptz,
  add column if not exists complained_at  timestamptz,
  add column if not exists last_event     text,
  add column if not exists bounce_type    text,
  add column if not exists diagnostic     text;

-- Events arrive keyed by provider message id, so that lookup must be fast.
create index if not exists article_deliveries_provider_message_id_idx
  on public.article_deliveries (provider_message_id);

-- ---- 3. Readable truth for the dashboard --------------------------------
-- Distinguishes "accepted" from "actually delivered", which is exactly the
-- distinction the load tests could not make.
create or replace view public.delivery_health as
select
  d.id                                                        as digest_id,
  d.sent_at,
  count(ad.id)                                                as accepted,
  count(ad.delivered_at)                                      as delivered,
  count(ad.bounced_at)                                        as bounced,
  count(ad.complained_at)                                     as complained,
  count(ad.id) - count(ad.delivered_at) - count(ad.bounced_at) as unconfirmed,
  round(100.0 * count(ad.delivered_at) / nullif(count(ad.id), 0), 1) as delivered_pct
from public.digests d
join public.article_deliveries ad on ad.digest_id = d.id
group by d.id, d.sent_at;

revoke all on public.delivery_health from anon, authenticated;
